version: '3.7'
services: 
    app:
        build: 
            context: ./..
            dockerfile: docker/php/Dockerfile
        restart: always
        volumes: 
            - ../app:/app
        networks: 
            - vk_feeder
    
    nginx:
        build: 
            context: ./..
            dockerfile: docker/nginx/Dockerfile
        restart: always
        ports: 
            - '6001:8080'
        networks: 
            - vk_feeder
        volumes: 
            - ../app:/app

networks: 
    vk_feeder:           