version: '3.7'
services: 
    vk-feeder:
        build: 
            context: ./..
            dockerfile: docker/php/Dockerfile
        restart: always
        volumes: 
            - ../app:/app
        networks: 
            - vk_feeder

    db:
        build: 
            context: ./..
            dockerfile: docker/db/Dockerfile
        restart: always
        networks: 
            - vk_feeder
        ports: 
            - '5432:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}


    adminer:
        build:
            context: ./..
            dockerfile: docker/adminer/Dockerfile
        restart: always
        ports:
            - 9000:8080
        networks: 
            - vk_feeder

networks: 
    vk_feeder:

volumes: 
    db-volume: